website/models.py
from . import db
import datetime

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key = True)  #primary key gives each task a new id
    task = db.Column(db.String(300), unique = True) #task to have a max entry of 300 characters and task must be unique
    complete = db.Column(db.Boolean, default = False)
    date_created = db.Column(db.String(10), default=datetime.date.today().strftime('%d-%m-%Y'))
    priority = db.Column(db.String, default = False)
    category = db.Column(db.String, default = False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'   #location of db
    db.init_app(app)

    from .views import my_view
    app.register_blueprint(my_view)

    from .models import Todo
    with app.app_context():
        db.create_all()
    
    return app

website/views.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, send_file
from flask_sqlalchemy import SQLAlchemy
import datetime
from .models import Todo
from . import db
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from io import BytesIO
import base64
from datetime import datetime
import dateutil.parser




my_view = Blueprint("my_view", __name__)
@my_view.route("/")
def home():
    todo_list = Todo.query.all()
    message = request.args.get("message", None) #Get any message or success parameter from the request URL
    success = request.args.get("success", None)
    return render_template("index.html", todo_list=todo_list, message = message, success = success)

@my_view.route("/add", methods=["POST"])    #allows post methods
def add():
    try:
        task = request.form.get("task").lower()     # Get the task from the form data
        priority = request.form.get("priority")
        category = request.form.get("category")
        new_todo = Todo(task=task, priority = priority, category=category)     # Create a new Todo object with the task
        db.session.add(new_todo)   #add into db
        db.session.commit() 
        success = "Task added successfully"    #
        return redirect(url_for("my_view.home", success = success))
    except:
        message = "Error adding your task to the ToDo list, you can not have more than one of the same task" # If an error occurs during adding the task, set an error message
        return redirect(url_for("my_view.home", message = message))

@my_view.route("/update/<todo_id>")
def update (todo_id):
    todo = Todo.query.filter_by(id=todo_id).first() # Find the todo item by its ID
    todo.complete = not todo.complete   # Toggle the completion status of the todo item
    db.session.commit() 
    return redirect(url_for("my_view.home"))

@my_view.route("/delete/<todo_id>")
def delete (todo_id):
    todo = Todo.query.filter_by(id=todo_id).first() # Find the todo item by its ID
    db.session.delete(todo) # Delete the todo item from the database
    db.session.commit()
    return redirect(url_for("my_view.home"))

@my_view.route("/edit/<int:todo_id>", methods=["GET", "POST"])
def edit_todo(todo_id):
    try:
        todo = Todo.query.get(todo_id)
        if request.method == "POST":    # If the request method is POST, update the task of the todo item
            todo.task = request.form["edit_task"]  # Corrected input field name
            db.session.commit()
            return redirect(url_for("my_view.home"))
        return render_template("edit_todo.html", todo=todo)
    except:
        message = "Error editing your task. Two identical tasks cannot exist"   # If an error occurs during editing the task, set an error message
        return redirect(url_for("my_view.home", message=message)) # Redirect to the home page with the error message


@my_view.route("/page2")
def page2():
    data = Todo.query.all()
    return render_template("page2.html", data = data)

@my_view.route("/graph")
def graph():
    
    completed_count = Todo.query.filter_by(complete=True).count()   # Query the database to get counts of completed and not completed tasks
    not_completed_count = Todo.query.filter_by(complete=False).count()
    
    plt.figure(figsize=(8, 6))  # Plotting the graph
    plt.bar(['Completed', 'Not Completed'], [completed_count, not_completed_count], color=['green', 'red'])
    plt.title('Tasks Completion Status')
    plt.xlabel('Status')
    plt.ylabel('Number of Tasks')
    plt.show()
    
    img = BytesIO() # Save the plot as a PNG image in memory
    plt.savefig(img, format='png')
    img.seek(0)
    plt.close()

    graph_url = base64.b64encode(img.getvalue()).decode()       # Convert the PNG image to base64 string

    return render_template('graph.html', graph_url=graph_url)       # Render the HTML template with the graph
    
@my_view.route("/graph2")
def graph2():
    dates = []
    tasks_count = []

    entries = Todo.query.all()
    for entry in entries:
        # Convert entry.date_created to a datetime object
        date_created = dateutil.parser.parse(entry.date_created)
        dates.append(date_created.strftime('%Y-%m-%d'))
        tasks_count = Todo.query.filter_by(complete=True).count()

    plt.figure(figsize=(8, 6))
    plt.bar(dates, tasks_count)
    plt.title('Completed Tasks by Date')
    plt.xlabel('Date')
    plt.ylabel('Number of Tasks Completed')

    img = BytesIO()
    plt.savefig(img, format='png')
    img.seek(0)
    plt.close()

    date_graph_url = base64.b64encode(img.getvalue()).decode()
    return render_template('graph2.html', date_graph_url=date_graph_url)

website/templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static', filename='style.css')}}">
    <title>To Do App</title>

<!--[if gte mso 9]><xml>
<mso:CustomDocumentProperties>
<mso:xd_Signature msdt:dt="string"></mso:xd_Signature>
<mso:display_urn_x003a_schemas-microsoft-com_x003a_office_x003a_office_x0023_Editor msdt:dt="string">Katy Long</mso:display_urn_x003a_schemas-microsoft-com_x003a_office_x003a_office_x0023_Editor>
<mso:Order msdt:dt="string">5379300.00000000</mso:Order>
<mso:xd_ProgID msdt:dt="string"></mso:xd_ProgID>
<mso:_ExtendedDescription msdt:dt="string"></mso:_ExtendedDescription>
<mso:display_urn_x003a_schemas-microsoft-com_x003a_office_x003a_office_x0023_Author msdt:dt="string">Katy Long</mso:display_urn_x003a_schemas-microsoft-com_x003a_office_x003a_office_x0023_Author>
<mso:ComplianceAssetId msdt:dt="string"></mso:ComplianceAssetId>
<mso:TemplateUrl msdt:dt="string"></mso:TemplateUrl>
<mso:ContentTypeId msdt:dt="string">0x0101006776E503C93961438855067381508F60</mso:ContentTypeId>
<mso:TriggerFlowInfo msdt:dt="string"></mso:TriggerFlowInfo>
<mso:_SourceUrl msdt:dt="string"></mso:_SourceUrl>
<mso:_SharedFileIndex msdt:dt="string"></mso:_SharedFileIndex>
</mso:CustomDocumentProperties>
</xml><![endif]-->
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do App</title>
</head>

<body>
    <nav>
        <a href ="{{url_for('my_view.home')}}">Home</a>
        <a href ="{{url_for('my_view.page2')}}">Entries</a>
        <a href="{{ url_for('my_view.graph') }}">Graph Page 1</a>
        <a href="{{ url_for('my_view.graph2') }}">Graph Page 2</a>
    </nav>

{% block content %}
{% endblock %}
</body>
</html>

website/templates/graph.html
{% extends 'base.html' %}

{% block content %}

<title>Graph</title>
</head>
<body>
    <h1>Graph</h1>
    <img src="data:image/png;base64,{{ graph_url }}" alt="Tasks Completion Graph">

{% endblock %}

website/templates/graph2.html
{% extends 'base.html' %}

{% block content %}

<title>Graph</title>
</head>
<body>
    <h1>Graph</h1>

    <img src="data:image/png;base64,{{ date_graph_url }}" alt="Tasks by Date Graph">
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

<p style="background-image: url('calendar.jpg');"> 

{% block content %}
    <div class="container">
        <h1>To Do List</h1>

        {% if message %}
        <p style="color: red;">{{ message }}</p>
        {% endif %}
        {% if success %}
        <p style="color: green;">{{ success }}</p>
        {% endif %}

        <form action="/add" method="post">
            <label for="task">Task:</label>
            <input type="text" id="task" name="task" placeholder="Enter a Task">
            <label for="priority">Priority:</label>
            <select id="priority" name="priority">
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
            </select>
            <label for="category">Category</label>
            <select id="category" name="category">
            <option value="general">General</option>
            <option value="work">Work</option>
            <option value="home">Home</option>
            </select>
        
        <button type="submit">Add Task</button>
        </form>

        <hr>
        

    
    {% for todo in todo_list %}
        <div class="todo-item">
            <p>Task {{ todo.id }}: {{ todo.task }} - {{ todo.date_created }} - Priority: {{ todo.priority }} - Category: {{ todo.category }} - Status: {% if todo.complete %}completed{% else %}incomplete{% endif %}</p>
            <div class="todo-buttons">
                {% if todo.complete == False %}
                    <a href="/update/{{ todo.id }}">Mark as complete</a>
                {% elif todo.complete == True %}
                    <a href="/update/{{ todo.id }}">Mark as incomplete</a>
                {% endif %}
                <a href="/delete/{{ todo.id }}">Delete</a>
                <form action="/edit/{{ todo.id }}" method="POST" style="display: inline;">
                    <label for="edit-task">Edit:</label>
                    <input type="text" id="edit-task" name="edit_task" placeholder="Edit your task">
                    <button type="submit">Save</button>
                </form>
                <a href="/priority/{{ todo.id }}"></a>
                
            
            </div>
        </div>
    {% endfor %}

{% endblock %}

website/templates/page2.html
{% extends 'base.html' %}

{% block content %}
    

    <div class="content">
        {% for data in data %}
            <div class="data">
                <p><b>#{{ data.id }}</b></p>
                <p class="name">{{ data.task }}</p>
                <p>Created: {{ data.date_created }}</p>
                <p>Priority: {{ data.priority }}</p>
                <p>Category: {{ data.category }}</p>
                {% if data.complete %}
                    <p>Status: Completed</p>
                {% else %}
                    <p>Status: Incomplete</p>
                {% endif %}
            </div>
        {% endfor %}


        <button onclick="printPage()" style="font-size: 16px; padding: 10px 20px;">Print</button>

        <script>
            function printPage() {
                window.print();
            }
        </script>
    </div>
{% endblock %}